# Generated by Django 5.2.4 on 2025-09-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
        ("stock", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="length_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.length_variation",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="stock.product"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseproduct",
            name="size_variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stock.size_variation",
            ),
        ),
    ]
