# Generated by Django 5.2.4 on 2025-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="Grand_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
