# Generated by Django 5.2.4 on 2025-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="length_variation",
            name="length_in_inch",
            field=models.CharField(max_length=20),
        ),
    ]
